/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 21-Jun.-2025 12:47:32 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */
create database dbYamboly

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_ComprobanteDePago_Pago]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [ComprobanteDePago] DROP CONSTRAINT [FK_ComprobanteDePago_Pago]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_DetalleDeVenta_Pedido]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [DetalleDeVenta] DROP CONSTRAINT [FK_DetalleDeVenta_Pedido]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_DetalleDeVenta_Producto]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [DetalleDeVenta] DROP CONSTRAINT [FK_DetalleDeVenta_Producto]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Empresa_Pedido]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Empresa] DROP CONSTRAINT [FK_Empresa_Pedido]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Pedido_ComprobanteDePago]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Pedido] DROP CONSTRAINT [FK_Pedido_ComprobanteDePago]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Pedido_MetodoDePago]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Pedido] DROP CONSTRAINT [FK_Pedido_MetodoDePago]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_ProductoPresentaciones_Presentaciones]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [ProductoPresentaciones] DROP CONSTRAINT [FK_ProductoPresentaciones_Presentaciones]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_ProductoPresentaciones_Producto]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [ProductoPresentaciones] DROP CONSTRAINT [FK_ProductoPresentaciones_Producto]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Ubigeo_Empresa]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Ubigeo] DROP CONSTRAINT [FK_Ubigeo_Empresa]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[ComprobanteDePago]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [ComprobanteDePago]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[DetalleDeVenta]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [DetalleDeVenta]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Empresa]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Empresa]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[MetodoDePago]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [MetodoDePago]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Pago]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Pago]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Pedido]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Pedido]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Presentaciones]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Presentaciones]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Producto]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Producto]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[ProductoPresentaciones]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [ProductoPresentaciones]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Ubigeo]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Ubigeo]
GO

/* Create Tables */

CREATE TABLE [ComprobanteDePago]
(
	[ComprobanteDePagoID] varchar(50) NOT NULL,
	[PagoID] int NOT NULL
)
GO

CREATE TABLE [DetalleDeVenta]
(
	[DetalleDeVentaID] varchar(150) NOT NULL,
	[PedidoID] varchar(100) NOT NULL,
	[ProductoID] varchar(25) NOT NULL
)
GO

CREATE TABLE [Empresa]
(
	[EmpresaID] varchar(30) NOT NULL,
	[PedidoID] varchar(100) NOT NULL
)
GO

CREATE TABLE [MetodoDePago]
(
	[MetodoDePagoID] varchar(25) NOT NULL
)
GO

CREATE TABLE [Pago]
(
	[PagoID] int NOT NULL
)
GO

CREATE TABLE [Pedido]
(
	[PedidoID] varchar(100) NOT NULL,
	[ComprobanteDePagoID] varchar(50) NOT NULL,
	[MetodoDePagoID] varchar(25) NOT NULL
)
GO

CREATE TABLE [Presentaciones]
(
	[PresentacionesID] varchar(40) NOT NULL
)
GO

CREATE TABLE [Producto]
(
	[ProductoID] varchar(25) NOT NULL
)
GO

CREATE TABLE [ProductoPresentaciones]
(
	[PresentacionesID] varchar(40) NULL,
	[ProductoID] varchar(25) NULL
)
GO

CREATE TABLE [Ubigeo]
(
	[UbigeoID] int NOT NULL,
	[EmpresaID] varchar(30) NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [ComprobanteDePago] 
 ADD CONSTRAINT [PK_ComprobanteDePago]
	PRIMARY KEY CLUSTERED ([ComprobanteDePagoID] ASC)
GO

ALTER TABLE [DetalleDeVenta] 
 ADD CONSTRAINT [PK_DetalleDeVenta]
	PRIMARY KEY CLUSTERED ([DetalleDeVentaID] ASC)
GO

ALTER TABLE [Empresa] 
 ADD CONSTRAINT [PK_Empresa]
	PRIMARY KEY CLUSTERED ([EmpresaID] ASC)
GO

ALTER TABLE [MetodoDePago] 
 ADD CONSTRAINT [PK_MetodoDePago]
	PRIMARY KEY CLUSTERED ([MetodoDePagoID] ASC)
GO

ALTER TABLE [Pago] 
 ADD CONSTRAINT [PK_Pago]
	PRIMARY KEY CLUSTERED ([PagoID] ASC)
GO

ALTER TABLE [Pedido] 
 ADD CONSTRAINT [PK_Pedido]
	PRIMARY KEY CLUSTERED ([PedidoID] ASC)
GO

ALTER TABLE [Presentaciones] 
 ADD CONSTRAINT [PK_Presentaciones]
	PRIMARY KEY CLUSTERED ([PresentacionesID] ASC)
GO

ALTER TABLE [Producto] 
 ADD CONSTRAINT [PK_Producto]
	PRIMARY KEY CLUSTERED ([ProductoID] ASC)
GO

ALTER TABLE [Ubigeo] 
 ADD CONSTRAINT [PK_Ubigeo]
	PRIMARY KEY CLUSTERED ([UbigeoID] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [ComprobanteDePago] ADD CONSTRAINT [FK_ComprobanteDePago_Pago]
	FOREIGN KEY ([PagoID]) REFERENCES [Pago] ([PagoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [DetalleDeVenta] ADD CONSTRAINT [FK_DetalleDeVenta_Pedido]
	FOREIGN KEY ([PedidoID]) REFERENCES [Pedido] ([PedidoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [DetalleDeVenta] ADD CONSTRAINT [FK_DetalleDeVenta_Producto]
	FOREIGN KEY ([ProductoID]) REFERENCES [Producto] ([ProductoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Empresa] ADD CONSTRAINT [FK_Empresa_Pedido]
	FOREIGN KEY ([PedidoID]) REFERENCES [Pedido] ([PedidoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Pedido] ADD CONSTRAINT [FK_Pedido_ComprobanteDePago]
	FOREIGN KEY ([ComprobanteDePagoID]) REFERENCES [ComprobanteDePago] ([ComprobanteDePagoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Pedido] ADD CONSTRAINT [FK_Pedido_MetodoDePago]
	FOREIGN KEY ([MetodoDePagoID]) REFERENCES [MetodoDePago] ([MetodoDePagoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [ProductoPresentaciones] ADD CONSTRAINT [FK_ProductoPresentaciones_Presentaciones]
	FOREIGN KEY ([PresentacionesID]) REFERENCES [Presentaciones] ([PresentacionesID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [ProductoPresentaciones] ADD CONSTRAINT [FK_ProductoPresentaciones_Producto]
	FOREIGN KEY ([ProductoID]) REFERENCES [Producto] ([ProductoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Ubigeo] ADD CONSTRAINT [FK_Ubigeo_Empresa]
	FOREIGN KEY ([EmpresaID]) REFERENCES [Empresa] ([EmpresaID]) ON DELETE No Action ON UPDATE No Action
GO

